import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/shared/Footer";
import { Header } from "@/components/shared/Header";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased font-[family-name:var(--font-geist-sans)]`}
      >
        <Header />
        <main className="overflow-hidden">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
